### ISSUE TITLE
find proper dataset

### ISSUE THREAD

**Issue by dancingsushii** [dancingsushii/geo-specific-diffpriv#2]

**Comment by mariidpm** [comment]
Dataset found by Inga:
https://www.kaggle.com/datasets/johnjdavisiv/us-counties-covid19-weather-sociohealth-data?resource=download
--
Dataset we uploaded (from above link) with the needed modifications to the database (as a table):
https://drive.google.com/file/d/1iQOPgSWpWGZFVEWHBhoXTmrBBnjaZWVQ/view?usp=sharing

**Comment by dancingsushii** [comment]
So we'll use this one further? I'm a little confused, is it ok that there is no personal data in it? Or are we going to sort of following the narrative that if you connect this dataset with other data, you can reveal private information? Or are we even going to find another one later? 😃

**Comment by mariidpm** [comment]
I think the location in general is considered personal data, as it can help identify a user (location in specific time) but we can double check tomorrow in the Q&A

**Comment by dancingsushii** [comment]
Resolved after discussion at QA.
